Repository DuGBB/trail-lad, pull requests merged in 2021-11, with the labels that each got.

#1 file structure
  assets/css/style.css
  assets/js/script.js
  index.html
Labels: enhancement

#21 Feature/local storage
  assets/js/script.js
Labels: bug, enhancement

#23 Alert/replace
  README.md
  assets/images/traillad.png
  assets/js/script.js
Labels: bug, enhancement

#25 checkbox vars left in were removed
  assets/js/script.js
Labels: bug

#28 links formatting
  assets/js/script.js
Labels: bug
